//Translation file generated by VNES
//DON'T EDIT THIS FILE!! The content of this file will be deleted.
//-> Make a copy and start your translation. Then, you can include your file into the project.

//SCRPT :
char* translation_script[] = {
	/*[2] "Here is a [wave]BBCODE[/wave] test !"*/
	"",
	/*[3] "Here is a [wave]BBCODE[/wave] test !
Here is a [wave]BBCODE[/wave] test !"*/
	"",
	/*[4] "~Whoooaaa~, this *effect* looks __**so cool**__ !"*/
	"",
	/*[5] "Tu trouves enfin **la pers*onne
que tu** cherch*ais."*/
	"",
	/*[10] "A Ah, tu es là!"*/
	"",
	/*[15] "A Ça me fait plaisir de te voir,
tu vas bien ?"*/
	"",
	/*[21] "A Moi aussi je vais bien,
très bien meme!"*/
	"",
	/*[23] "A J'avais un peu peur qu'on
arrive pas a se retrouver,"*/
	"",
	/*[24] "A mais finalement il n'y avait
pas a s'inquieter!"*/
	"",
	/*[30] "A Ne t'excuse pas, tu es là
c'est l'essentiel!"*/
	"",
	/*[34] "A Et j'ai pu profiter du
paysage en attendant!"*/
	"",
	/*[40] "A Haha, mes indications etaient
si vagues que ca?"*/
	"",
	/*[44] "A Desole, je ne connais pas
beaucoup la region."*/
	"",
	/*[48] "A Mais je trouvais cette plage
pas trop mal."*/
	"",
	/*[50] "A Au moins ici on est au calme!"*/
	"",
	/*[54] "Son attention se porte alors
sur la mer."*/
	"",
	/*[55] "Elle est calme, reguliere,
et s'etend a perte de vue."*/
	"",
	/*[58] "A C'est beau,
tu ne trouves pas?"*/
	"",
	/*[542] "En effet, en arrivant tu as     cru entendre de la musique."*/
	"",
	/*[549] "En portant ton attention, tu    repere mieux les sons de la     ville."*/
	"",
	/*[550] "D'ici, vous entendez des        chants et des bruits festifs"*/
	"",
	/*[551] "Il doit y avoir beaucoup de     monde la bas."*/
	"",
	/*[552] "Et c'est peut-etre pour ca      que la plage est deserte."*/
	"",
	/*[727] "Vous avancez tranquillement     vers la ville cotiere."*/
	"",
	/*[728] "Une musique festive vient       a vos oreilles."*/
	"",
	/*[729] "C'est bien l'epoque du          festival annuel,"*/
	"",
	/*[730] "et la foule s'en donne          a coeur joie."*/
	"",
	/*[731] "Tu t'assures qu'Ange est        toujours derriere toi."*/
	"",
	/*[735] "Tu progresses dans la ville en  direction du stand de glace."*/
	"",
	/*[736] "Autour de vous volent           confettis et feux d'artifice."*/
	"",
	/*[737] "Le gros de la foule danse sur   la place principale."*/
	"",
	/*[738] "Tu comprends mieux pourquoi     la plage etait si vide."*/
	"",
	/*[739] "Tu arrives enfin a la boutique  de glace."*/
	"",
	/*[740] "Apres inspection du menu,       tu te tournes vers Ange."*/
	"",
	/*[742] "Mais en te retournant,          tu ne vois personne."*/
	"",
	/*[743] "Ange n'est plus derriere toi."*/
	"",
	/*[744] "Tu sors rapidement de la        boutique."*/
	"",
	/*[745] "Personne."*/
	"",
	/*[746] "Misere, Ange t'a surement       perdu en chemin."*/
	"",
	/*[747] "L'esprit plein d'inquietude,    tu entames tes recherches."*/
	"",
	/*[749] "Tu interpelles un passant,      esperant avoir des info."*/
	"",
	/*[750] ""Quelqu'un avec un pull gris?   Ici c'pas commun haha""*/
	"",
	/*[751] ""Maintenant tout le monde porte la collection estivale!""*/
	"",
	/*[752] ""La classe pas vrai? Attends    de voir ma nouvelle dance!""*/
	"",
	/*[753] ""Il survivra ton pull gris,     viens faire la fete!""*/
	"",
	/*[754] "Ce type etait sympathique,      mais ne t'a pas avance."*/
	"",
	/*[755] "Les gens ici sont trop occupes  a faire la fete pour t'aider."*/
	"",
	/*[757] "Si Ange t'a perdu, c'est        surement a cause de la foule."*/
	"",
	/*[758] "Bravement, tu te glisses entre  les danseurs a sa recherche."*/
	"",
	/*[759] "Tu vois bien que tu genes,      mais c'est au nom de l'amitie."*/
	"",
	/*[760] "Sur la place, tu grimpes sur    la fontaine centrale."*/
	"",
	/*[761] "Te surelever t'aidera plus      dans tes recherches."*/
	"",
	/*[762] "Tu surplombes la foule du       regard, mais sans succes."*/
	"",
	/*[763] "Pourtant ses vetements gris     sont facilement reperables,"*/
	"",
	/*[764] "Surtout dans la maree de        costumes colores."*/
	"",
	/*[765] "Tu scrutes une derniere fois    la foule, au cas ou."*/
	"",
	/*[766] "Mais tu te resous finalement a  changer de strategie."*/
	"",
	/*[768] "Tu rebrousses chemin jusqu'a    la plage."*/
	"",
	/*[769] "Peut-etre qu'Ange est quelque   part sur la route."*/
	"",
	/*[770] "Tu fais attention a regarder    partout autour de toi."*/
	"",
	/*[771] "Inspectant ruelles et detours   au cas ou Ange y serait."*/
	"",
	/*[772] "Tu sors de la ville,            et toujours aucune trace."*/
	"",
	/*[773] "Mais de retour sur la plage,    tu retrouves un visage familier."*/
	"",
	/*[912] "Son attention se porte de       nouveau vers l'horizon."*/
	"",
	/*[913] "Le jour est a present bien      avance,"*/
	"",
	/*[914] "et le soleil descend            progressivement dans le ciel."*/
	"",
	/*[915] "Ses rayons se refletent         etrangement sur l'eau bleue."*/
	"",
	/*[916] "C'est vraiment un beau          spectacle."*/
	"",
	/*[917] "Soudain, Ange remarque          quelque chose a l'horizon."*/
	"",
	/*[1062] "   "*/
	"",
	/*[1063] "Connexion perdue..."*/
	"",
	/*[1064] "Ange s'est deconnecte"*/
	"",
};

//MENU :
char* translation_menu[] = {
//CHOICE-------
	/*[0][0] "BTN1"*/
	"",
	/*[0][1] "BTN2"*/
	"",
	/*[0][2] "BTN3"*/
	"",
	/*[0][3] "BTN4"*/
	"",
//PAUSE-------
	/*[1][0] "Volume"*/
	"",
	/*[1][1] "Mute"*/
	"",
	/*[1][2] "CPS"*/
	"",
	/*[1][3] "Autre menu"*/
	"",
	/*[1][4] "SAVE"*/
	"",
	/*[1][5] "LOAD"*/
	"",
//SUBMENU-------
	/*[2][0] "BTN1"*/
	"",
	/*[2][1] "Slider"*/
	"",
	/*[2][2] "RETOUR"*/
	"",
// -------
	/*[3][0] "NEW GAME"*/
	"",
	/*[3][1] "LOAD GAME"*/
	"",
};

