//Translation

void ExportTranslation() //TODO: add a function to escape some characters (\n,\t,%...)
{
  FILE* translation_file;
  translation_file = fopen("./translation/translation_file.h", "w");
  fprintf_s(translation_file, "//Translation file generated by VNES\n");
  fprintf_s(translation_file, "//DON'T EDIT THIS FILE!! The content of this file will be deleted.\n//-> Make a copy and start your translation. Then, you can include your file into the project.\n\n");
  fprintf_s(translation_file, "//SCRPT :\n");
  fprintf_s(translation_file, "char* translation_script[] = {\n");
  for (int i = 0; i < sizeof(SCRPT)/sizeof(SCRPT[0]); i++)
  {
    if (SCRPT[i].t == N)
    {
      fprintf_s(translation_file, "\t/*[%d] \"%s\"*/\n",i,SCRPT[i].c);
      fprintf_s(translation_file, "\t\"\",\n");
    }
  }
  fprintf_s(translation_file, "};\n\n");

  fprintf_s(translation_file, "//MENU :\n");
  fprintf_s(translation_file, "char* translation_menu[] = {\n");
  for (int i_page = 0; i_page < MenuPageNumber; i_page++)
  {
    fprintf_s(translation_file, "//%s-------\n", ListMenuPage[i_page].title);
    for (int i_item = 0; i_item < MAX_ITEMS_MENU_PAGE; i_item++)
    {
      if (ListMenuPage[i_page].items[i_item].label != NULL)
      {
        fprintf_s(translation_file, "\t/*[%d][%d] \"%s\"*/\n",i_page, i_item, ListMenuPage[i_page].items[i_item].label);
        fprintf_s(translation_file, "\t\"\",\n");

      }
    }    
  }
  fprintf_s(translation_file, "};\n\n");

  

  fclose(translation_file);
  
}
